"""Stops at the max-token limit on the solver and the judge side, per benchmark and solver (tab_conditions.tex).

One row per benchmark x solver model for the four thinking-mode solvers
Qwen3.5-{4B,9B} and gemma-4-{E2B,E4B}-it at the 16k solver budget: the share
of solver generations that stop at the max-token limit, and per judge (Gemma4,
Qwen3.6, both at a 16k judge budget) the share of its judgments that stop at
the judge's limit together with Pass@k_max - CoT-Pass@k_max under that judge.
Stop shares come from the recorded finish state of every generation
(solver_capped_count and judge_capped_count in report.csv). Both inputs,
report.csv and gap_curve.csv, are in analysis/data; the table is written to
analysis/tables.
"""

import pandas as pd
from common import TAB_DIR, data, ensure_output_dirs

REPORT = data("report.csv")
GAP = data("gap_curve.csv")
OUT = TAB_DIR / "tab_conditions.tex"
JUDGE_FULL = {"Gemma4": "gemma-4-26B-A4B-it", "Qwen3.6": "Qwen3.6-35B-A3B"}

BUDGET = 16384
MODELS = ["Qwen3.5-4B", "Qwen3.5-9B", "gemma-4-E2B-it", "gemma-4-E4B-it"]
SHORT = {"Qwen3.5-4B": "Q3.5-4B", "Qwen3.5-9B": "Q3.5-9B", "gemma-4-E2B-it": "G4-E2B", "gemma-4-E4B-it": "G4-E4B"}
# benchmark, short label, k_max
BM = [
    ("aime2026", "AIME (EN)", 64),
    ("aime2026_pt", "AIME (PT)", 64),
    ("aime2026_tr", "AIME (TR)", 64),
    ("tubitak_math2026", "TÜB\\.ITAK (TR)", 64),
    ("pt_exams_math", "PT exams", 16),
]

HEADER = """% GENERATED by analysis/src/tab_conditions.py; do not edit by hand.
\\begin{table}[!htbp]
\\centering
\\footnotesize
\\setlength{\\tabcolsep}{2pt}
\\begin{tabular}{llrrrrr}
\\toprule
 & & \\multicolumn{1}{c}{solver} & \\multicolumn{2}{c}{Gemma4} &
\\multicolumn{2}{c}{Qwen3.6} \\\\
\\cmidrule(lr){4-5}\\cmidrule(lr){6-7}
Benchmark & Solver & \\multicolumn{1}{c}{stops} & stops &
\\multicolumn{1}{c}{diff.} & stops & \\multicolumn{1}{c}{diff.} \\\\
\\midrule
"""
FOOTER = """\\bottomrule
\\end{tabular}
\\caption{Stops at the max-token limit on both sides, in thinking mode at the 16k generation
budget: the share of solver generations that stop at the max-token limit
(stops, \\%), and per judge the share of its judgments that do, with the
difference Pass@$k_{\\max}$ $-$ CoT-Pass@$k_{\\max}$ (diff.) under that
judge. $k_{\\max}$ is 64, or 16 for the Portuguese exams; stop rates come
from each generation's recorded finish state. Q3.5 = Qwen3.5,
G4 = Gemma-4-it.}
\\label{tab:conditions}
\\end{table}
"""


def load():
    r = pd.read_csv(REPORT, low_memory=False)
    g = pd.read_csv(GAP)
    r = r[(r.state == "think") & (r.solver_max_tokens == BUDGET) & (r.model.isin(MODELS))]
    g = g[
        (g.state == "think")
        & (g.solver_max_tokens == BUDGET)
        & (g.solver_model.isin(MODELS))
        & (g.judge_short.isin(JUDGE_FULL))
        & (g.judge_max_tokens == BUDGET)
    ]
    return r, g


def gap(g, model, bench, k, judge):
    """Pass@k - CoT-Pass@k in points for one solver x benchmark cell under one judge."""
    d = g[(g.solver_model == model) & (g.benchmark == bench) & (g.k == k) & (g.judge_short == judge)]
    assert len(d) == 1, (bench, k, judge, len(d))
    return 100 * (d.pass_at_k.iloc[0] - d.cot_pass_at_k.iloc[0])


def solver_stop(r, model, bench):
    """Share of solver generations that stop at the solver's max-token limit, from the unjudged row."""
    d = r[(r.model == model) & (r.benchmark == bench) & (r.judge_model.isna())]
    assert len(d) == 1, (bench, len(d))
    return 100 * d.solver_capped_count.sum() / d.n_generations_with_text.sum()


def judge_stop(r, model, bench, judge):
    """Share of judge generations that stop at the judge's max-token limit."""
    d = r[
        (r.model == model)
        & (r.benchmark == bench)
        & (r.judge_max_tokens == BUDGET)
        & (r.judge_model.astype(str).str.endswith(JUDGE_FULL[judge]))
    ]
    assert len(d) == 1, (model, bench, judge, len(d))
    return 100 * d.judge_capped_count.iloc[0] / d.n_verdicts.iloc[0]


def main():
    ensure_output_dirs()
    r, g = load()
    rows = []
    print("benchmark x solver model, thinking mode at 16k:")
    for bench, short, kmax in BM:
        for j, m in enumerate(MODELS):
            s = solver_stop(r, m, bench)
            jg = judge_stop(r, m, bench, "Gemma4")
            jq = judge_stop(r, m, bench, "Qwen3.6")
            delta = gap(g, m, bench, kmax, "Qwen3.6")
            delta_g4 = gap(g, m, bench, kmax, "Gemma4")
            print(
                f"  {bench:18s} {m:16s} solver@limit={s:5.1f}%  Gemma4@limit={jg:5.1f}%  "
                f"Qwen3.6@limit={jq:4.1f}%  delta_g4={delta_g4:5.2f}  delta={delta:5.2f}"
            )
            rows.append(
                (
                    short if j == 0 else "",
                    SHORT[m],
                    f"{s:.1f}",
                    f"{jg:.1f}",
                    f"{delta_g4:.2f}",
                    f"{jq:.1f}",
                    f"{delta:.2f}",
                    j == len(MODELS) - 1,
                )
            )

    with open(OUT, "w") as f:
        f.write(HEADER)
        for i, (name, mdl, s, jg, dg, jq, dl, last) in enumerate(rows):
            f.write(f"{name} & {mdl} & {s} & {jg} & {dg} & {jq} & {dl} \\\\\n")
            if last and i < len(rows) - 1:
                f.write("\\addlinespace[2pt]\n")
        f.write(FOOTER)
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
