"""Pass@64 - CoT-Pass@64 per solver under every judge that covers it (tab_judge_matrix.tex).

Two stacked tables with different judge columns, because judge coverage is
complementary: the earlier generation under Qwen3.6, Gemma4, V4-Flash and
R1-distill, the current generation under Qwen3.6 and Gemma4. Each entry is the
question-weighted average over the four 64-sample benchmarks at the 16k solver
budget; the last row of each table averages the solvers. The numbers come
from gap_curve.csv in analysis/data and the table goes to analysis/tables.
"""

import pandas as pd
from common import TAB_DIR, data, ensure_output_dirs

CSV = data("gap_curve.csv")
OUT = TAB_DIR / "tab_judge_matrix.tex"

BM = ["aime2026", "aime2026_pt", "aime2026_tr", "tubitak_math2026"]
BLOCKS = [
    (
        "Earlier generation (Qwen2.5)",
        ["Qwen3.6", "Gemma4", "V4-Flash", "R1-distill"],
        [
            ("Q2.5-7B", "Qwen2.5-7B", "base"),
            ("Q2.5-32B", "Qwen2.5-32B", "base"),
            ("Q2.5-7B-I", "Qwen2.5-7B-Instruct", "non-think"),
            ("Q2.5-32B-I", "Qwen2.5-32B-Instruct", "non-think"),
        ],
    ),
    (
        "Current generation (Qwen3.5, Gemma-4)",
        ["Qwen3.6", "Gemma4"],
        [
            ("Q3.5-4B-B", "Qwen3.5-4B-Base", "base"),
            ("Q3.5-9B-B", "Qwen3.5-9B-Base", "base"),
            ("Q3.5-4B", "Qwen3.5-4B", "non-think"),
            ("Q3.5-9B", "Qwen3.5-9B", "non-think"),
            ("G4-E2B", "gemma-4-E2B-it", "non-think"),
            ("G4-E4B", "gemma-4-E4B-it", "non-think"),
        ],
    ),
]
CAPTIONS = [
    (
        """Pass@64 $-$ CoT-Pass@64 per earlier-generation solver (rows),
averaged over the four 64-sample benchmarks (weighted by how many
questions each contributes, as in Figures~\\ref{fig:k-ladder}
and~\\ref{fig:bootstrap}) under all four judges
(columns). Judge generation budgets: 16{,}384 for Qwen3.6, Gemma4 and
R1-distill, 20{,}480 for V4-Flash; every judge runs in thinking mode with
three judgments per solution. The last row averages the solvers.
Q2.5 = Qwen2.5 (-I Instruct).""",
        "tab:judge-matrix-earlier",
    ),
    (
        """As Table~\\ref{tab:judge-matrix-earlier}, for the
current-generation solvers under the two judges that cover them.
Q3.5 = Qwen3.5 (-B base), G4 = Gemma-4-it.""",
        "tab:judge-matrix-current",
    ),
]


def load():
    g = pd.read_csv(CSV)
    return g[(g.benchmark.isin(BM)) & (g.k == 64) & (g.solver_max_tokens == 16384)]


def diff(g, model, state, judge):
    """Question-weighted Pass@64 - CoT-Pass@64 over the four benchmarks, in points."""
    d = g[(g.solver_model == model) & (g.state == state) & (g.judge_short == judge)]
    d = d.drop_duplicates(["benchmark"])
    assert len(d) == 4, (model, judge, len(d))
    w = d.n_tasks
    return 100 * ((d.pass_at_k - d.cot_pass_at_k) * w).sum() / w.sum()


def main():
    ensure_output_dirs()
    g = load()
    lines = ["% GENERATED by analysis/src/tab_judge_matrix.py; do not edit."]
    for (title, judges, members), (cap, lab) in zip(BLOCKS, CAPTIONS, strict=False):
        cols = "l" + "r" * len(judges)
        head = " & ".join(judges)
        lines += [
            "\\begin{table}[!htbp]",
            "\\centering",
            "\\footnotesize",
            "\\setlength{\\tabcolsep}{3pt}",
            f"\\begin{{tabular}}{{{cols}}}",
            "\\toprule",
            f"Solver & {head} \\\\",
            "\\midrule",
        ]
        print(title)
        block_vals = []
        for label, model, state in members:
            vals = [diff(g, model, state, j) for j in judges]
            block_vals.append(vals)
            print(f"  {label:20s}" + "".join(f"{v:9.1f}" for v in vals))
            lines.append(f"{label} & " + " & ".join(f"{v:.1f}" for v in vals) + " \\\\")
        avgs = [sum(v[i] for v in block_vals) / len(block_vals) for i in range(len(judges))]
        print(f"  {'Average':20s}" + "".join(f"{v:9.1f}" for v in avgs))
        lines += ["\\midrule", "Average & " + " & ".join(f"{v:.1f}" for v in avgs) + " \\\\"]
        lines += ["\\bottomrule", "\\end{tabular}", f"\\caption{{{cap}}}", f"\\label{{{lab}}}", "\\end{table}"]
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
