"""The same thirty AIME problems in three languages, in both generation modes (tab_language.tex).

Qwen3.5-{4B,9B} at the 16k generation budget on the three AIME benchmarks
(the English original and its Portuguese and Turkish translations), in
non-thinking and thinking mode. Columns give the share of generations that
stop at the max-token limit, Pass@1 and Pass@64, averaged over questions and
over the two models. The Turkish olympiad and the Portuguese exams are
different problems and stay out.

Everything comes from report.csv in analysis/data; the table is written to
analysis/tables/tab_language.tex.
"""

import pandas as pd
from common import TAB_DIR, data, ensure_output_dirs

REPORT = data("report.csv")
OUT = TAB_DIR / "tab_language.tex"

MODELS = ["Qwen3.5-4B", "Qwen3.5-9B"]
BM = [("aime2026", "EN"), ("aime2026_pt", "PT"), ("aime2026_tr", "TR")]
MODES = [("non-think", "non-thinking"), ("think", "thinking")]

HEADER = (
    "% GENERATED by analysis/src/tab_language.py; do not edit by hand.\n"
    "\\begin{table}[!htbp]\n\\centering\n\\footnotesize\n"
    "\\setlength{\\tabcolsep}{3pt}\n"
    "\\begin{tabular}{llrrr}\n\\toprule\n"
    "Mode & Lang. & \\multicolumn{1}{c}{stops at max} &"
    " \\multicolumn{1}{c}{Pass@1} & \\multicolumn{1}{c}{Pass@64} \\\\\n"
    " & & \\multicolumn{1}{c}{tokens (\\%)} &"
    " \\multicolumn{1}{c}{(\\%)} & \\multicolumn{1}{c}{(\\%)} \\\\\n"
    "\\midrule\n"
)
FOOTER = """\\bottomrule
\\end{tabular}
\\caption{The same thirty AIME problems in English and in the Portuguese
and Turkish translations: Qwen3.5-\\{4B,9B\\} at the 16k generation budget,
both modes. Columns give the share of generations that stop at the
max-token limit, Pass@1 and Pass@64, averaged over questions and over the
two models.}
\\label{tab:language}
\\end{table}
"""


def main():
    ensure_output_dirs()
    r = pd.read_csv(REPORT, low_memory=False)
    r = r[(r.judge_model.isna()) & (r.solver_max_tokens == 16384) & (r.model.isin(MODELS))]

    rows = []
    for state, label in MODES:
        for bench, lang in BM:
            d = r[(r.state == state) & (r.benchmark == bench)]
            assert len(d) == len(MODELS), (state, bench, len(d))
            assert set(d.n_tasks) == {30}, d.n_tasks.tolist()
            cap = 100 * d.solver_capped_count.sum() / d.n_generations_with_text.sum()
            p1 = 100 * d["pass@1"].mean()
            p64 = 100 * d["pass@64"].mean()
            print(f"  {label:12s} {lang}  at limit {cap:5.1f}  Pass@1 {p1:5.1f}  Pass@64 {p64:5.1f}")
            rows.append((label if lang == "EN" else "", lang, cap, p1, p64))

    with open(OUT, "w") as f:
        f.write(HEADER)
        for i, (label, lang, cap, p1, p64) in enumerate(rows):
            if label and i:
                f.write("\\addlinespace[2pt]\n")
            f.write(f"{label} & {lang} & {cap:.1f} & {p1:.1f} & {p64:.1f} \\\\\n")
        f.write(FOOTER)
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
