"""The budget ladder: the same solver on the same benchmark at its low and high generation budget (tab_ladder.tex).

Rows are benchmark x solver for Qwen3.5-{4B,9B} in thinking mode on the four
64-sample benchmarks. The low budget is 16,384 tokens everywhere; the high
budget is 32,768, except 65,536 on English AIME. Columns give the share of
solver generations stopping at the max-token limit, Pass@1 and Pass@64 at both
budgets. Pass@64 - CoT-Pass@64 under the anchor judge Qwen3.6 is not a column,
but the script asserts that it is exactly zero in every cell at both budgets.
The judge budget is 16,384 at the low rung and 32,768 at the high rung.
Solver numbers come from report.csv and the differences from gap_curve.csv,
both in analysis/data; the table goes to analysis/tables.
"""

import pandas as pd
from common import TAB_DIR, data, ensure_output_dirs

REPORT = data("report.csv")
GAP = data("gap_curve.csv")
OUT = TAB_DIR / "tab_ladder.tex"

MODELS = [("Qwen3.5-4B", "4B"), ("Qwen3.5-9B", "9B")]
# benchmark, label, high solver budget
BM = [
    ("aime2026", "AIME (EN)", 65536),
    ("aime2026_pt", "AIME (PT)", 32768),
    ("aime2026_tr", "AIME (TR)", 32768),
    ("tubitak_math2026", "TÜB\\.ITAK (TR)", 32768),
]
# judge budget paired with each solver budget
JBUD = {16384: 16384, 32768: 32768, 65536: 32768}

HEADER = (
    "% GENERATED by analysis/src/tab_ladder.py; do not edit by hand.\n"
    "\\begin{table}[!htbp]\n\\centering\n\\footnotesize\n"
    "\\setlength{\\tabcolsep}{2pt}\n"
    "\\begin{tabular}{llrrrrrr}\n\\toprule\n"
    " & & \\multicolumn{2}{c}{stops at max} & \\multicolumn{2}{c}{Pass@1} &"
    " \\multicolumn{2}{c}{Pass@64} \\\\\n"
    " & & \\multicolumn{2}{c}{tokens (\\%)} & \\multicolumn{2}{c}{(\\%)} &"
    " \\multicolumn{2}{c}{(\\%)} \\\\\n"
    "\\cmidrule(lr){3-4}\\cmidrule(lr){5-6}\\cmidrule(lr){7-8}\n"
    "Benchmark & Solver & low & high & low & high & low & high \\\\\n"
    "\\midrule\n"
)
FOOTER = """\\bottomrule
\\end{tabular}
\\caption{The budget ladder: the same solver on the same benchmark at its
low and high generation budget. Low is 16{,}384 tokens everywhere; high is
32{,}768, except 65{,}536 on English AIME (the text explains the jump).
Share of solver generations stopping at the max-token limit, Pass@$1$ and
Pass@$64$; thinking mode throughout. 4B/9B = Qwen3.5.}
\\label{tab:ladder}
\\end{table}
"""


def solver_cell(r, m, b, sm):
    """(stop share, Pass@1, Pass@64) in percent from the unjudged row at solver budget sm."""
    d = r[
        (r.state == "think")
        & (r.judge_model.isna())
        & (r.model == m)
        & (r.benchmark == b)
        & (r.solver_max_tokens == sm)
    ]
    assert len(d) == 1, (m, b, sm, len(d))
    return (100 * d.solver_cap_rate.iloc[0], 100 * d["pass@1"].iloc[0], 100 * d["pass@64"].iloc[0])


def diff_cell(g, m, b, sm):
    """Pass@64 - CoT-Pass@64 in points under the anchor judge Qwen3.6 at solver budget sm."""
    d = g[
        (g.judge_short == "Qwen3.6")
        & (g.state == "think")
        & (g.solver_model == m)
        & (g.benchmark == b)
        & (g.solver_max_tokens == sm)
        & (g.judge_max_tokens == JBUD[sm])
        & (g.k == 64)
    ]
    assert len(d) == 1, (m, b, sm, len(d))
    return 100 * (d.pass_at_k.iloc[0] - d.cot_pass_at_k.iloc[0])


def main():
    ensure_output_dirs()
    r = pd.read_csv(REPORT, low_memory=False)
    g = pd.read_csv(GAP)

    rows = []
    print("Ladder (low, high per row):")
    for b, bname, hi in BM:
        for m, mshort in MODELS:
            s_lo, p1_lo, p64_lo = solver_cell(r, m, b, 16384)
            s_hi, p1_hi, p64_hi = solver_cell(r, m, b, hi)
            dl = diff_cell(g, m, b, 16384)
            dh = diff_cell(g, m, b, hi)
            assert abs(dl) < 1e-9 and abs(dh) < 1e-9, f"Pass@64 - CoT-Pass@64 nonzero in ({m}, {b}): {dl} / {dh}"
            hilab = "64k" if hi == 65536 else "32k"
            rows.append(
                (
                    bname,
                    mshort,
                    f"{s_lo:.1f}",
                    f"{s_hi:.1f}",
                    f"{p1_lo:.1f}",
                    f"{p1_hi:.1f}",
                    f"{p64_lo:.1f}",
                    f"{p64_hi:.1f}",
                )
            )
            print(
                f"  {bname:16s} {mshort} 16k,{hilab:3s}  stop {s_lo:5.1f},{s_hi:5.1f}  "
                f"p1 {p1_lo:5.1f},{p1_hi:5.1f}  p64 {p64_lo:5.1f},{p64_hi:5.1f}  "
                f"diff {dl:.2f},{dh:.2f} (asserted zero, not in table)"
            )

    with open(OUT, "w") as f:
        f.write(HEADER)
        prev_b = None
        for bname, mshort, s_lo, s_hi, p1_lo, p1_hi, p64_lo, p64_hi in rows:
            label = bname if bname != prev_b else ""
            if bname != prev_b and prev_b is not None:
                f.write("\\addlinespace[2pt]\n")
            prev_b = bname
            f.write(f"{label} & {mshort} & {s_lo} & {s_hi} & {p1_lo} & {p1_hi} & {p64_lo} & {p64_hi} \\\\\n")
        f.write(FOOTER)
    print(f"\nwrote {OUT}")


if __name__ == "__main__":
    main()
